[package]
name = "cash-relay"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
actix-cors = "0.2.0"
actix-files = "0.2.1"
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-service = "1.0.1"
base64 = "0.11.0"
bitcoin = "0.21.0"
bitcoincash-addr = "0.5.0"
bitcoin_hashes = "0.7.3"
bytes = "0.5.3"
clap = { version = "2.33.0", features = ["yaml"] }
config = "0.10.1"
dirs = "2.0.2"
env_logger = "0.7.1"
futures = "0.3.1"
hex = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.8"
prost = { git = "https://github.com/danburkert/prost" }
reqwest = { git = "https://github.com/seanmonstar/reqwest", features = ["json"] }
rocksdb = "0.13.0"
secp256k1 = { version = "0.17.1", features = ["rand"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
sha2 = "0.8.0"
subtle = "2.2.2"
url = "2.1.0"

[build-dependencies]
prost-build = { git = "https://github.com/danburkert/prost" }
