[package]
name = "cash-relay"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"
description = "Cash:web Relay is a end-to-end encrypted message relay server"

[dependencies]
base64 = "0.11.0"
bitcoin = "0.23.0"
bitcoincash-addr = "0.5.1"
bitcoin_hashes = "0.7.4"
bytes = "0.5.3"
clap = { version = "2.33.0", features = ["yaml"] }
config = "0.10.1"
dirs = "2.0.2"
futures = "0.3.1"
hex = "0.4.0"
lazy_static = "1.4.0"
parking_lot = "0.10.0"
prost = "0.6.1"
rocksdb = "0.13.0"
secp256k1 = { version = "0.17.2", features = ["rand-std"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
sha2 = "0.8.1"
subtle = "2.2.2"
tokio = { version = "0.2.11", features = ["blocking",  "macros", "rt-core", "rt-threaded"]}
url = "2.1.1"
warp = "0.2.1"

[build-dependencies]
prost-build = "0.6.1"
