[package]
name = "cash-relay"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
bitcoincash-addr = "0.4.0"
bytes = "0.5.3"
hyper = "0.13.1"
futures-core = "0.3.1"
futures-util = "0.3.1"
prost = { git = "https://github.com/danburkert/prost" }
rocksdb = "0.13.0"
sha2 = "0.8.0"
tower-service = "0.3.0"

[build-dependencies]
prost-build = { git = "https://github.com/danburkert/prost" }
